### PR TITLE
Added: Common and helpful interaction and extension methods (SpecFlow.Actions.Playwright, SpecFlow.Actions.Selenium).

### PR DESCRIPTION
**Pull request by Sven-Seyfert**
### SpecFlow.Actions.Playwright

Added:
- Common interaction method GetUrl() which is also implemented in the Selenium implementation.
Useful for a comparison of the Selenium implementation versus the Playwright ones.
- Interaction method GetUrl() to Readme.md file.

Changed:
- String "Selenium" to "Playwright" in summary comment.

Removed:
- Selenium package reference.

Tests:
- All CalculatorFeature test scenarios still works (passed).

### SpecFlow.Actions.Selenium

Added:
- Common extension method MoveToElement() which moves the mouse/viewport to the specific element.
- Extension method MoveToElement() to Readme.md file.

Changed:
- Package update for ChromeDriver.
- Var to Const.

Removed:
- Conditional access qualifier, because the expression is known to be not null.

Tests:
- All CalculatorFeature test scenarios still works (passed).
- Also the Unit Tests still works (passed).

### CODE REVIEW

**Comment by Sven-Seyfert** [comment]
Sorry the second commit should actually be a second pull request but I missed it.
Anyway, I am pretty sure you will handle it 🤞 .

**Comment by JordanWestern** [comment]
Thanks @Sven-Seyfert we will take a look :)

**Comment by Sven-Seyfert** [comment]
@JordanWestern 

## My guess why it breaks
Maybe the build error "dotnet test [...]" is caused by a missing package reference update:

grafik

I didn't commited my package update change which I mad locally, because I thought it will be made automatically in the build pipeline.

**ChromeDriver update**
grafik

**Comment by SabotageAndi** [comment]
Thanks for your contribution to SpecFlow. 
Please submit your contributions to our SpecFlow Community Heroes program at https://specflow.org/community/submit-a-contribution/

**Pull request merged**
